"""Script 14 - Run Phase 1 LLM inference over generated prompt records.

Supports two backends:
    - vllm: actual model inference with a chat template
    - mock: deterministic JSON responses for dry-run and schema smoke tests

Resume behavior:
    - Existing run_ids in the output JSON are preserved.
    - Missing run_ids are processed in batches and checkpointed after each batch.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
from pathlib import Path
from typing import Any

import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", ".."))

from common import (
    DRY_RUN_SAMPLES,
    INFERENCE_RECORD_COLUMNS,
    PROMPT_RECORD_COLUMNS,
    PROJECT_ROOT,
    atomic_write_json,
    existing_run_ids,
    extract_json_object,
    load_json_records,
)


INPUT_JSON = PROJECT_ROOT / "data" / "processed" / "tardis" / "phase1_outputs" / "phase1_prompts.json"
DRY_RUN_INPUT_JSON = PROJECT_ROOT / "data" / "processed" / "tardis" / "phase1_outputs" / "phase1_prompts.dry_run.json"
OUTPUT_JSON = PROJECT_ROOT / "data" / "processed" / "tardis" / "phase1_outputs" / "raw_elicited.json"
DRY_RUN_OUTPUT_JSON = PROJECT_ROOT / "data" / "processed" / "tardis" / "phase1_outputs" / "raw_elicited.dry_run.json"
DEFAULT_MODEL_PATH = PROJECT_ROOT / "models" / "mistral-7b-instruct"
JSON_ONLY_STOP_SEQUENCES = ["\nExplanation:", "\n\nExplanation:", "\n```", "```"]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run Phase 1 LLM inference")
    parser.add_argument("--input-json", type=Path, default=None,
                        help="Prompt JSON generated by script 13")
    parser.add_argument("--output-json", type=Path, default=None,
                        help="Output JSON for raw elicited responses")
    parser.add_argument("--model-path", type=Path, default=DEFAULT_MODEL_PATH,
                        help="Local model directory for the vLLM backend")
    parser.add_argument("--backend", choices=["auto", "vllm", "mock"], default="auto",
                        help="Inference backend. Auto prefers vLLM when available.")
    parser.add_argument("--batch-size", type=int, default=32,
                        help="Prompts per generation batch")
    parser.add_argument("--max-retries", type=int, default=3,
                        help="Retry count for malformed responses")
    parser.add_argument("--temperature", type=float, default=0.8,
                        help="Sampling temperature")
    parser.add_argument("--max-tokens", type=int, default=400,
                        help="Maximum completion tokens")
    parser.add_argument("--gpu-memory-utilization", type=float, default=0.85,
                        help="vLLM GPU memory utilization cap")
    parser.add_argument("--max-model-len", type=int, default=4096,
                        help="Maximum model context length")
    parser.add_argument("--quantization", default=None,
                        help="Optional vLLM quantization mode such as awq")
    parser.add_argument("--seed", type=int, default=20260501,
                        help="Seed for deterministic mock responses")
    parser.add_argument("--overwrite", action="store_true",
                        help="Ignore existing output and rerun all prompts")
    parser.add_argument("--dry-run", action="store_true",
                        help="Run on 3 prompt records and write a dry-run output file")
    return parser.parse_args()


def choose_paths(args: argparse.Namespace) -> tuple[Path, Path]:
    input_json = args.input_json or (DRY_RUN_INPUT_JSON if args.dry_run else INPUT_JSON)
    output_json = args.output_json or (DRY_RUN_OUTPUT_JSON if args.dry_run else OUTPUT_JSON)
    return input_json, output_json


def validate_prompt_records(records: list[dict[str, Any]]) -> None:
    if not records:
        raise ValueError("No prompt records found")
    missing_columns = [column for column in PROMPT_RECORD_COLUMNS if column not in records[0]]
    if missing_columns:
        raise ValueError(f"Prompt records are missing expected columns: {missing_columns}")


def resolve_backend(args: argparse.Namespace) -> str:
    if args.backend == "mock":
        return "mock"
    if args.backend == "vllm":
        return "vllm"

    if args.model_path.exists():
        try:
            import vllm  # noqa: F401
            import transformers  # noqa: F401
            return "vllm"
        except ImportError:
            pass
    return "mock"


def batched(records: list[dict[str, Any]], batch_size: int) -> list[list[dict[str, Any]]]:
    return [records[index:index + batch_size] for index in range(0, len(records), batch_size)]


def render_chat_prompt(record: dict[str, Any], tokenizer: Any | None = None) -> str:
    messages = record.get("messages") or [
        {"role": "system", "content": record["system_prompt"]},
        {"role": "user", "content": record["user_prompt"]},
    ]
    if tokenizer is None:
        rendered = []
        for message in messages:
            rendered.append(f"[{message['role'].upper()}]\n{message['content']}")
        rendered.append("[ASSISTANT]")
        return "\n\n".join(rendered)
    return tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)


def mock_response(record: dict[str, Any], seed: int) -> str:
    digest = hashlib.sha256(f"mock:{seed}:{record['run_id']}".encode("utf-8")).hexdigest()
    rng = np.random.default_rng(int(digest[:16], 16))

    agent_type = record["agent_type"]
    phase = record["phase"]
    ofi = float(record.get("ofi_sample") or 0.0)
    stress = float(record.get("stress_proxy") or 0.0)
    overshoot = abs(float(record.get("drop_from_local_pct_sample") or 0.0))
    realized_vol = float(record.get("realized_vol_50_sample") or 0.0)

    phase_shift = {"pre": 0.0, "drop": 0.15, "recovery": -0.05, "post": -0.1}[phase]
    noise = float(rng.normal(0.0, 0.08))

    aggressiveness = 0.5
    cancel_probability = 0.05
    order_size_multiplier = 1.0
    inventory_sensitivity = 0.1
    order_type = "market"
    side = "do_nothing"
    reasoning = "Signal is mixed, so exposure stays light."

    if agent_type == "momentum_trader":
        aggressiveness = np.clip(0.62 + phase_shift + 0.12 * np.tanh(abs(ofi)) + noise, 0.05, 0.98)
        cancel_probability = np.clip(0.03 + 0.01 * rng.random(), 0.0, 0.12)
        inventory_sensitivity = np.clip(0.08 + 0.05 * rng.random(), 0.01, 0.45)
        order_size_multiplier = np.clip(0.9 + 0.6 * stress + 0.2 * rng.normal(), 0.1, 5.0)
        order_type = "market"
        if phase == "drop" or ofi < -0.5:
            side = "sell"
            reasoning = "Bearish flow and elevated stress support a continuation sell."
        elif phase == "recovery" and ofi >= 0:
            side = "buy"
            reasoning = "Flow is stabilizing, so the recovery case supports a cautious buy."
        elif abs(ofi) < 0.15 and stress < 1.0:
            side = "do_nothing"
            reasoning = "Edge is weak, so waiting is better than forcing a trade."
        else:
            side = "buy" if ofi > 0 else "sell"
            reasoning = "Directional flow is strong enough to justify a momentum trade."
    elif agent_type == "contrarian_trader":
        aggressiveness = np.clip(0.35 + 6.0 * overshoot + 0.08 * rng.normal(), 0.05, 0.98)
        cancel_probability = np.clip(0.04 + 0.02 * rng.random(), 0.0, 0.2)
        inventory_sensitivity = np.clip(0.12 + 0.08 * rng.random(), 0.01, 0.6)
        order_size_multiplier = np.clip(0.8 + 10.0 * overshoot + 0.15 * rng.normal(), 0.1, 5.0)
        order_type = "market"
        if overshoot < 0.01 and stress < 1.1:
            side = "do_nothing"
            reasoning = "The overshoot is below the activation threshold, so no trade."
        elif ofi <= 0:
            side = "buy"
            reasoning = "Selling pressure looks stretched, so the contrarian leans into a buy."
        else:
            side = "sell"
            reasoning = "The move looks overbought, so fading it with a sell is consistent."
    elif agent_type == "hft_market_maker":
        aggressiveness = np.clip(0.18 + 0.08 * stress + 0.05 * rng.normal(), 0.01, 0.75)
        cancel_probability = np.clip(0.32 + 0.18 * rng.random(), 0.05, 0.85)
        inventory_sensitivity = np.clip(0.1 + 0.07 * rng.random(), 0.01, 0.65)
        order_size_multiplier = np.clip(0.35 + 0.15 * rng.random(), 0.1, 2.0)
        order_type = "limit"
        if stress > 1.8:
            side = "do_nothing"
            reasoning = "Adverse selection risk is high, so the safest choice is to stand down."
        elif ofi < 0:
            side = "buy"
            reasoning = "Quoting the bid side helps warehouse inventory against selling pressure."
        else:
            side = "sell"
            reasoning = "Quoting the ask side helps keep inventory close to flat."
    elif agent_type == "noise_trader":
        random_signal = float(rng.normal()) * max(realized_vol, 1e-4)
        aggressiveness = np.clip(0.4 + 0.15 * rng.random(), 0.05, 0.9)
        cancel_probability = np.clip(0.01 + 0.01 * rng.random(), 0.0, 0.08)
        inventory_sensitivity = np.clip(0.04 + 0.05 * rng.random(), 0.01, 0.35)
        order_size_multiplier = np.clip(0.7 + abs(random_signal) * 100 + 0.2 * rng.normal(), 0.1, 5.0)
        order_type = "market"
        if abs(random_signal) < max(realized_vol, 1e-4):
            side = "do_nothing"
            reasoning = "The random draw is too small to justify a trade this cycle."
        else:
            side = "buy" if random_signal > 0 else "sell"
            reasoning = "A volatility-scaled random draw produces a blind market order."

    payload = {
        "aggressiveness": round(float(aggressiveness), 6),
        "cancel_probability": round(float(cancel_probability), 6),
        "order_size_multiplier": round(float(order_size_multiplier), 6),
        "inventory_sensitivity": round(float(inventory_sensitivity), 6),
        "order_type": order_type,
        "side": side,
        "reasoning_summary": reasoning,
    }
    return json.dumps(payload, ensure_ascii=False)


def build_vllm_runtime(args: argparse.Namespace) -> tuple[Any, Any, Any]:
    try:
        from transformers import AutoTokenizer
        from vllm import LLM, SamplingParams
    except ImportError as exc:
        raise ImportError(
            "vLLM backend requested but vllm/transformers is not installed in the current Python environment"
        ) from exc

    if not args.model_path.exists():
        raise FileNotFoundError(f"Model path not found: {args.model_path}")

    tokenizer = AutoTokenizer.from_pretrained(args.model_path)
    llm = LLM(
        model=str(args.model_path),
        quantization=args.quantization,
        gpu_memory_utilization=args.gpu_memory_utilization,
        max_model_len=args.max_model_len,
    )
    sampling_params = SamplingParams(
        temperature=args.temperature,
        max_tokens=args.max_tokens,
        seed=args.seed,
        stop=JSON_ONLY_STOP_SEQUENCES,
    )
    return tokenizer, llm, sampling_params


def generate_batch_vllm(
    batch: list[dict[str, Any]],
    tokenizer: Any,
    llm: Any,
    sampling_params: Any,
) -> list[str]:
    prompts = [render_chat_prompt(record, tokenizer) for record in batch]
    outputs = llm.generate(prompts, sampling_params)
    rendered: list[str] = []
    for output in outputs:
        completion = ""
        if getattr(output, "outputs", None):
            completion = output.outputs[0].text
        rendered.append(completion)
    return rendered


def process_batch(
    batch: list[dict[str, Any]],
    backend: str,
    args: argparse.Namespace,
    runtime: tuple[Any, Any, Any] | None,
) -> list[dict[str, Any]]:
    attempts = {record["run_id"]: 0 for record in batch}
    pending = list(batch)
    results: dict[str, dict[str, Any]] = {}

    while pending:
        current_batch = list(pending)
        pending = []
        if backend == "mock":
            responses = [mock_response(record, args.seed) for record in current_batch]
        else:
            tokenizer, llm, sampling_params = runtime  # type: ignore[misc]
            responses = generate_batch_vllm(current_batch, tokenizer, llm, sampling_params)

        for record, response_text in zip(current_batch, responses):
            run_id = record["run_id"]
            attempts[run_id] += 1
            payload, parse_error = extract_json_object(response_text)
            if payload is None and attempts[run_id] < args.max_retries:
                pending.append(record)
                continue

            enriched = dict(record)
            enriched.update(
                {
                    "model_name": args.model_path.name if backend == "vllm" else "mock-phase1-backend",
                    "backend": backend,
                    "temperature": args.temperature,
                    "max_tokens": args.max_tokens,
                    "attempt_count": attempts[run_id],
                    "inference_status": "ok" if payload is not None else f"retry_exhausted:{parse_error}",
                    "raw_response_text": response_text,
                }
            )
            results[run_id] = {column: enriched.get(column) for column in INFERENCE_RECORD_COLUMNS}

    return [results[record["run_id"]] for record in batch]


def main() -> None:
    args = parse_args()
    input_json, output_json = choose_paths(args)

    prompt_records = load_json_records(input_json)
    validate_prompt_records(prompt_records)

    if args.dry_run:
        prompt_records = prompt_records[:DRY_RUN_SAMPLES]

    existing_records = [] if args.overwrite else load_json_records(output_json)
    existing_ids = existing_run_ids(existing_records)
    pending_records = [record for record in prompt_records if record["run_id"] not in existing_ids]

    backend = resolve_backend(args)
    runtime = None
    if backend == "vllm":
        runtime = build_vllm_runtime(args)

    records = list(existing_records)

    print("=" * 70)
    print("Script 14: Run Phase 1 Inference")
    print("=" * 70)
    print(f"  Input        : {input_json}")
    print(f"  Output       : {output_json}")
    print(f"  Backend      : {backend}")
    print(f"  Model path   : {args.model_path}")
    print(f"  Batch size   : {args.batch_size}")
    print(f"  Max retries  : {args.max_retries}")
    print(f"  Existing     : {len(existing_records)} records")
    print(f"  Pending      : {len(pending_records)} records")
    if args.dry_run and backend == "mock":
        print("  [INFO] Dry-run is using the deterministic mock backend because vLLM is unavailable or auto-disabled.")

    for batch_number, batch in enumerate(batched(pending_records, args.batch_size), start=1):
        batch_results = process_batch(batch, backend=backend, args=args, runtime=runtime)
        records.extend(batch_results)
        atomic_write_json(output_json, records)
        ok_count = sum(1 for record in batch_results if str(record["inference_status"]) == "ok")
        print(f"  Batch {batch_number:02d}: {ok_count}/{len(batch_results)} valid JSON responses")

    records = sorted(records, key=lambda record: str(record["run_id"]))
    atomic_write_json(output_json, records)

    statuses: dict[str, int] = {}
    for record in records:
        status = str(record.get("inference_status"))
        statuses[status] = statuses.get(status, 0) + 1

    print("\n  Status counts:")
    for status, count in sorted(statuses.items()):
        print(f"    - {status:30s} {count:>3d}")
    print(f"\n  Total output records: {len(records)}")
    print("Done.")


if __name__ == "__main__":
    main()