"""Script 15 - Extract and validate elicited parameters from raw LLM output."""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path
from typing import Any

import pandas as pd

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", ".."))

from common import (
    DRY_RUN_SAMPLES,
    INFERENCE_RECORD_COLUMNS,
    PARSED_RECORD_COLUMNS,
    PROJECT_ROOT,
    existing_run_ids,
    extract_json_object,
    load_json_records,
)


INPUT_JSON = PROJECT_ROOT / "data" / "processed" / "tardis" / "phase1_outputs" / "raw_elicited.json"
DRY_RUN_INPUT_JSON = PROJECT_ROOT / "data" / "processed" / "tardis" / "phase1_outputs" / "raw_elicited.dry_run.json"
OUTPUT_CSV = PROJECT_ROOT / "data" / "processed" / "tardis" / "phase1_outputs" / "raw_elicited.csv"
DRY_RUN_OUTPUT_CSV = PROJECT_ROOT / "data" / "processed" / "tardis" / "phase1_outputs" / "raw_elicited.dry_run.csv"
ERROR_LOG = PROJECT_ROOT / "data" / "processed" / "tardis" / "phase1_outputs" / "extract_errors.log"
DRY_RUN_ERROR_LOG = PROJECT_ROOT / "data" / "processed" / "tardis" / "phase1_outputs" / "extract_errors.dry_run.log"

NUMERIC_FIELD_ALIASES = {
    "aggressiveness": ["aggressiveness"],
    "cancel_probability": ["cancel_probability", "cancel_prob"],
    "order_size_multiplier": ["order_size_multiplier", "order_size", "size_multiplier"],
    "inventory_sensitivity": ["inventory_sensitivity", "inventory_sensitivity_vg"],
}
STRING_FIELD_ALIASES = {
    "order_type": ["order_type"],
    "side": ["side", "action"],
    "reasoning_summary": ["reasoning_summary", "reason", "summary"],
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Extract structured parameters from raw elicited responses")
    parser.add_argument("--input-json", type=Path, default=None,
                        help="Raw elicited JSON generated by script 14")
    parser.add_argument("--output-csv", type=Path, default=None,
                        help="Destination CSV for parsed parameters")
    parser.add_argument("--error-log", type=Path, default=None,
                        help="Destination log for failed parses")
    parser.add_argument("--overwrite", action="store_true",
                        help="Ignore any existing CSV and parse all raw records again")
    parser.add_argument("--dry-run", action="store_true",
                        help="Process only 3 raw records and write dry-run outputs")
    return parser.parse_args()


def choose_paths(args: argparse.Namespace) -> tuple[Path, Path, Path]:
    input_json = args.input_json or (DRY_RUN_INPUT_JSON if args.dry_run else INPUT_JSON)
    output_csv = args.output_csv or (DRY_RUN_OUTPUT_CSV if args.dry_run else OUTPUT_CSV)
    error_log = args.error_log or (DRY_RUN_ERROR_LOG if args.dry_run else ERROR_LOG)
    return input_json, output_csv, error_log


def validate_inference_records(records: list[dict[str, Any]]) -> None:
    if not records:
        raise ValueError("No raw elicited records found")
    missing_columns = [column for column in INFERENCE_RECORD_COLUMNS if column not in records[0]]
    if missing_columns:
        raise ValueError(f"Raw elicited records are missing expected columns: {missing_columns}")


def load_existing_csv(path: Path) -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame(columns=PARSED_RECORD_COLUMNS)
    frame = pd.read_csv(path)
    if frame.empty:
        return pd.DataFrame(columns=PARSED_RECORD_COLUMNS)
    return frame


def atomic_write_csv(path: Path, frame: pd.DataFrame) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temp_path = path.with_suffix(path.suffix + ".tmp")
    frame.to_csv(temp_path, index=False)
    temp_path.replace(path)


def write_error_log(path: Path, frame: pd.DataFrame) -> None:
    failed = frame[frame["parse_status"] != "parsed"].copy()
    lines = []
    for _, row in failed.iterrows():
        lines.append(f"{row['run_id']}\t{row['parse_error']}")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def first_present(payload: dict[str, Any], keys: list[str]) -> Any:
    for key in keys:
        if key in payload:
            return payload[key]
    return None


def to_bounded_float(value: Any, field_name: str, minimum: float, maximum: float) -> float:
    try:
        numeric = float(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{field_name} is not numeric") from exc
    if numeric < minimum or numeric > maximum:
        raise ValueError(f"{field_name} out of bounds [{minimum}, {maximum}]")
    return round(numeric, 6)


def normalize_payload(payload: dict[str, Any]) -> dict[str, Any]:
    normalized: dict[str, Any] = {}
    normalized["aggressiveness"] = to_bounded_float(
        first_present(payload, NUMERIC_FIELD_ALIASES["aggressiveness"]),
        "aggressiveness",
        0.0,
        1.0,
    )
    normalized["cancel_probability"] = to_bounded_float(
        first_present(payload, NUMERIC_FIELD_ALIASES["cancel_probability"]),
        "cancel_probability",
        0.0,
        1.0,
    )
    normalized["order_size_multiplier"] = to_bounded_float(
        first_present(payload, NUMERIC_FIELD_ALIASES["order_size_multiplier"]),
        "order_size_multiplier",
        0.1,
        5.0,
    )
    normalized["inventory_sensitivity"] = to_bounded_float(
        first_present(payload, NUMERIC_FIELD_ALIASES["inventory_sensitivity"]),
        "inventory_sensitivity",
        0.0,
        1.0,
    )

    order_type = str(first_present(payload, STRING_FIELD_ALIASES["order_type"]) or "").strip().lower()
    side = str(first_present(payload, STRING_FIELD_ALIASES["side"]) or "").strip().lower()
    reasoning_summary = str(first_present(payload, STRING_FIELD_ALIASES["reasoning_summary"]) or "").strip()

    if order_type not in {"market", "limit"}:
        raise ValueError("order_type must be one of {market, limit}")
    if side not in {"buy", "sell", "do_nothing"}:
        raise ValueError("side must be one of {buy, sell, do_nothing}")
    if not reasoning_summary:
        raise ValueError("reasoning_summary is empty")

    normalized["order_type"] = order_type
    normalized["side"] = side
    normalized["reasoning_summary"] = reasoning_summary[:240]
    return normalized


def parse_record(record: dict[str, Any]) -> dict[str, Any]:
    parsed_record = {column: record.get(column) for column in PARSED_RECORD_COLUMNS}
    parsed_record.update(
        {
            "parse_status": "failed",
            "parse_error": None,
            "aggressiveness": None,
            "cancel_probability": None,
            "order_size_multiplier": None,
            "inventory_sensitivity": None,
            "order_type": None,
            "side": None,
            "reasoning_summary": None,
        }
    )

    payload, parse_error = extract_json_object(str(record.get("raw_response_text") or ""))
    if payload is None:
        parsed_record["parse_error"] = parse_error
        return parsed_record

    try:
        normalized = normalize_payload(payload)
    except ValueError as exc:
        parsed_record["parse_error"] = str(exc)
        return parsed_record

    parsed_record.update(normalized)
    parsed_record["parse_status"] = "parsed"
    parsed_record["parse_error"] = ""
    return parsed_record


def print_summary(frame: pd.DataFrame) -> None:
    parsed_mask = frame["parse_status"] == "parsed"
    parsed_count = int(parsed_mask.sum())
    total_count = int(len(frame))
    failed_count = total_count - parsed_count
    parse_rate = 100.0 * parsed_count / total_count if total_count else 0.0

    print(f"\n  Parsed {parsed_count}/{total_count} ({parse_rate:.2f}%), Failed: {failed_count}")
    if total_count:
        breakdown = (
            frame.groupby(["agent_type", "phase", "parse_status"]).size().rename("count").reset_index()
        )
        print("  Breakdown by agent_type, phase, parse_status:")
        for _, row in breakdown.iterrows():
            print(
                f"    - {row['agent_type']:18s} {row['phase']:8s} "
                f"{row['parse_status']:8s} {int(row['count']):>3d}"
            )


def main() -> None:
    args = parse_args()
    input_json, output_csv, error_log = choose_paths(args)

    raw_records = load_json_records(input_json)
    validate_inference_records(raw_records)
    if args.dry_run:
        raw_records = raw_records[:DRY_RUN_SAMPLES]

    existing_frame = pd.DataFrame(columns=PARSED_RECORD_COLUMNS) if args.overwrite else load_existing_csv(output_csv)
    existing_ids = existing_run_ids(existing_frame.to_dict("records")) if not existing_frame.empty else set()
    pending_records = [record for record in raw_records if record["run_id"] not in existing_ids]

    print("=" * 70)
    print("Script 15: Extract Parameters")
    print("=" * 70)
    print(f"  Input      : {input_json}")
    print(f"  Output CSV : {output_csv}")
    print(f"  Error log  : {error_log}")
    print(f"  Existing   : {len(existing_frame)} rows")
    print(f"  Pending    : {len(pending_records)} rows")

    parsed_rows = [parse_record(record) for record in pending_records]
    new_frame = pd.DataFrame(parsed_rows, columns=PARSED_RECORD_COLUMNS)
    combined = pd.concat([existing_frame, new_frame], ignore_index=True)
    combined = combined.drop_duplicates(subset=["run_id"], keep="last").sort_values("run_id").reset_index(drop=True)

    atomic_write_csv(output_csv, combined)
    write_error_log(error_log, combined)
    print_summary(combined)
    print("\nDone.")


if __name__ == "__main__":
    main()