"""Script 16 - Fit Phase 1 behavioral priors from parsed elicitation output."""

from __future__ import annotations

import argparse
import json
import math
import os
import sys
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", ".."))

from common import AGENT_CONFIGS, DRY_RUN_SAMPLES, PARSED_RECORD_COLUMNS, PHASES, PROJECT_ROOT, atomic_write_json


INPUT_CSV = PROJECT_ROOT / "data" / "processed" / "tardis" / "phase1_outputs" / "raw_elicited.csv"
DRY_RUN_INPUT_CSV = PROJECT_ROOT / "data" / "processed" / "tardis" / "phase1_outputs" / "raw_elicited.dry_run.csv"
OUTPUT_JSON = PROJECT_ROOT / "data" / "processed" / "tardis" / "phase1_outputs" / "behavioral_priors.json"
DRY_RUN_OUTPUT_JSON = PROJECT_ROOT / "data" / "processed" / "tardis" / "phase1_outputs" / "behavioral_priors.dry_run.json"
ANCHORS_JSON = PROJECT_ROOT / "data" / "processed" / "tardis" / "confounder_outputs" / "prior_anchors.json"
MIN_GROUP_SIZE = 10
EPSILON = 1e-6


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Fit Phase 1 behavioral prior distributions")
    parser.add_argument("--input-csv", type=Path, default=None,
                        help="Parsed elicitation CSV generated by script 15")
    parser.add_argument("--output-json", type=Path, default=None,
                        help="Destination JSON for fitted behavioral priors")
    parser.add_argument("--anchors-json", type=Path, default=ANCHORS_JSON,
                        help="prior_anchors.json for scalar anchor defaults")
    parser.add_argument("--min-group-size", type=int, default=MIN_GROUP_SIZE,
                        help="Minimum parsed rows required before fitting a phase-specific distribution")
    parser.add_argument("--overwrite", action="store_true",
                        help="Accepted for interface symmetry; output is always rewritten")
    parser.add_argument("--dry-run", action="store_true",
                        help="Use the dry-run CSV and write a dry-run JSON output")
    return parser.parse_args()


def choose_paths(args: argparse.Namespace) -> tuple[Path, Path]:
    input_csv = args.input_csv or (DRY_RUN_INPUT_CSV if args.dry_run else INPUT_CSV)
    output_json = args.output_json or (DRY_RUN_OUTPUT_JSON if args.dry_run else OUTPUT_JSON)
    return input_csv, output_json


def load_frame(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Parsed CSV not found: {path}")
    frame = pd.read_csv(path)
    missing_columns = [column for column in PARSED_RECORD_COLUMNS if column not in frame.columns]
    if missing_columns:
        raise ValueError(f"Parsed CSV missing expected columns: {missing_columns}")
    return frame


def load_anchors(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"Anchor JSON not found: {path}")
    return json.loads(path.read_text(encoding="utf-8"))


def try_import_scipy() -> Any | None:
    try:
        from scipy import stats
        return stats
    except ImportError:
        return None


def fit_beta(values: np.ndarray, stats_module: Any | None) -> dict[str, Any]:
    clipped = np.clip(values.astype(float), EPSILON, 1.0 - EPSILON)
    mean = float(np.mean(clipped))
    var = float(np.var(clipped, ddof=1)) if len(clipped) > 1 else 0.0

    if stats_module is not None and len(clipped) > 1 and var > 1e-8:
        try:
            alpha, beta, _, _ = stats_module.beta.fit(clipped, floc=0.0, fscale=1.0)
            return {"dist": "beta", "params": {"alpha": round(float(alpha), 6), "beta": round(float(beta), 6)}}
        except Exception:
            pass

    if var <= 1e-8:
        concentration = 50.0
        alpha = max(mean * concentration, EPSILON)
        beta = max((1.0 - mean) * concentration, EPSILON)
    else:
        common = max(mean * (1.0 - mean) / var - 1.0, 2.0)
        alpha = max(mean * common, EPSILON)
        beta = max((1.0 - mean) * common, EPSILON)
    return {"dist": "beta", "params": {"alpha": round(alpha, 6), "beta": round(beta, 6)}}


def fit_gamma(values: np.ndarray, stats_module: Any | None) -> dict[str, Any]:
    clipped = np.clip(values.astype(float), EPSILON, None)
    mean = float(np.mean(clipped))
    var = float(np.var(clipped, ddof=1)) if len(clipped) > 1 else 0.0

    if stats_module is not None and len(clipped) > 1 and var > 1e-10:
        try:
            shape, _, scale = stats_module.gamma.fit(clipped, floc=0.0)
            return {"dist": "gamma", "params": {"shape": round(float(shape), 6), "scale": round(float(scale), 6)}}
        except Exception:
            pass

    if var <= 1e-10:
        shape = 100.0
        scale = mean / shape if mean > 0 else EPSILON
    else:
        shape = max(mean * mean / var, EPSILON)
        scale = max(var / mean, EPSILON)
    return {"dist": "gamma", "params": {"shape": round(shape, 6), "scale": round(scale, 6)}}


def fit_lognorm(values: np.ndarray, stats_module: Any | None) -> dict[str, Any]:
    clipped = np.clip(values.astype(float), EPSILON, None)
    if stats_module is not None and len(clipped) > 1:
        try:
            shape, loc, scale = stats_module.lognorm.fit(clipped, floc=0.0)
            return {
                "dist": "lognorm",
                "params": {
                    "shape": round(float(shape), 6),
                    "loc": round(float(loc), 6),
                    "scale": round(float(scale), 6),
                },
            }
        except Exception:
            pass

    logged = np.log(clipped)
    shape = float(np.std(logged, ddof=1)) if len(logged) > 1 else 0.0
    scale = float(np.exp(np.mean(logged)))
    return {
        "dist": "lognorm",
        "params": {"shape": round(shape, 6), "loc": 0.0, "scale": round(scale, 6)},
    }


def scalar_value(value: float) -> dict[str, Any]:
    return {"dist": "scalar", "params": {"value": round(float(value), 6)}}


def parsed_only(frame: pd.DataFrame) -> pd.DataFrame:
    parsed = frame[frame["parse_status"] == "parsed"].copy()
    if parsed.empty:
        return parsed
    if "sample_origin" in parsed.columns:
        parsed = parsed[parsed["sample_origin"] != "anchor_imputed_phase_sample"].copy()
        if parsed.empty:
            return parsed
    numeric_columns = [
        "aggressiveness",
        "cancel_probability",
        "order_size_multiplier",
        "inventory_sensitivity",
        "noise_trader_lambda_anchor",
        "spread_bps_sample",
        "leverage_proxy_sample",
        "drop_from_local_pct_sample",
    ]
    for column in numeric_columns:
        if column in parsed.columns:
            parsed[column] = pd.to_numeric(parsed[column], errors="coerce")
    return parsed


def choose_fit_frame(
    parsed: pd.DataFrame,
    agent_type: str,
    phase: str,
    min_group_size: int,
) -> tuple[pd.DataFrame, str, list[str]]:
    warnings: list[str] = []
    phase_frame = parsed[(parsed["agent_type"] == agent_type) & (parsed["phase"] == phase)].copy()
    if phase_frame.empty:
        warnings.append("no observed parsed rows for this agent-phase; excluded from fitting")
        return phase_frame, "excluded_missing_phase", warnings

    if len(phase_frame) >= min_group_size:
        return phase_frame, "phase_fit", warnings

    warnings.append(
        f"phase sample size {len(phase_frame)} is below {min_group_size}; falling back to agent-level fit"
    )

    agent_frame = parsed[parsed["agent_type"] == agent_type].copy()
    if len(agent_frame) >= min_group_size:
        return agent_frame, "agent_fallback", warnings

    warnings.append("agent-level sample size is also below threshold; using spec defaults")
    return phase_frame, "spec_default", warnings


def fit_common_behavior(
    fit_frame: pd.DataFrame,
    agent_type: str,
    fit_source: str,
    stats_module: Any | None,
) -> dict[str, Any]:
    defaults = AGENT_CONFIGS[agent_type]["fallback_priors"]
    if fit_source == "spec_default" or fit_frame.empty:
        return {
            "aggressiveness": defaults["aggressiveness"],
            "cancel_probability": defaults["cancel_probability"],
            "order_size_multiplier": defaults["order_size_multiplier"],
            "inventory_sensitivity_vg": defaults["inventory_sensitivity_vg"],
            "order_type_market_fraction": defaults["order_type_market_fraction"],
        }

    market_fraction = float((fit_frame["order_type"] == "market").mean()) if len(fit_frame) else 0.0
    return {
        "aggressiveness": fit_beta(fit_frame["aggressiveness"].dropna().to_numpy(), stats_module),
        "cancel_probability": fit_beta(fit_frame["cancel_probability"].dropna().to_numpy(), stats_module),
        "order_size_multiplier": fit_lognorm(fit_frame["order_size_multiplier"].dropna().to_numpy(), stats_module),
        "inventory_sensitivity_vg": fit_gamma(fit_frame["inventory_sensitivity"].dropna().to_numpy(), stats_module),
        "order_type_market_fraction": scalar_value(market_fraction),
    }


def contrarian_estar_params(phase_frame: pd.DataFrame) -> dict[str, Any] | None:
    usable = phase_frame.dropna(subset=["drop_from_local_pct_sample", "order_size_multiplier"])
    if usable.empty:
        return None
    threshold = 1.0
    top_cut = usable["order_size_multiplier"].quantile(0.75)
    high_commitment = usable[usable["order_size_multiplier"] >= top_cut]
    if high_commitment.empty:
        high_commitment = usable
    max_commitment_pct = float(np.median(np.abs(high_commitment["drop_from_local_pct_sample"].to_numpy())))
    max_commitment_pct = max(max_commitment_pct, threshold)
    return {
        "dist": "non_linear_thresholds",
        "params": {
            "activation_threshold_pct": round(threshold, 6),
            "max_size_commitment_deviation_pct": round(max_commitment_pct, 6),
        },
    }


def build_agent_specific_priors(
    agent_type: str,
    phase: str,
    phase_frame: pd.DataFrame,
    common_behavior: dict[str, Any],
    anchors: dict[str, Any],
) -> dict[str, Any]:
    defaults = AGENT_CONFIGS[agent_type]["fallback_priors"]

    if agent_type == "momentum_trader":
        return {
            "aggressiveness": common_behavior["aggressiveness"],
            "cancel_probability": common_behavior["cancel_probability"],
            "inventory_sensitivity_vg": common_behavior["inventory_sensitivity_vg"],
            "order_type_market_fraction": common_behavior["order_type_market_fraction"],
        }

    if agent_type == "contrarian_trader":
        estar = contrarian_estar_params(phase_frame) or {
            "dist": "non_linear_thresholds",
            "params": {
                "activation_threshold_pct": defaults["estar_activation_threshold_pct"]["params"]["value"],
                "max_size_commitment_deviation_pct": defaults["max_size_commitment_deviation_pct"]["params"]["value"],
            },
        }
        return {
            "inventory_sensitivity_vg": common_behavior["inventory_sensitivity_vg"],
            "aggressiveness_estar": estar,
            "order_type_market_fraction": common_behavior["order_type_market_fraction"],
        }

    if agent_type == "hft_market_maker":
        positive_spread = phase_frame["spread_bps_sample"].dropna()
        if positive_spread.empty:
            event_trigger = defaults["event_trigger_price_bps"]["params"]["value"]
        else:
            event_trigger = float(np.clip(np.median(np.abs(positive_spread.to_numpy())), 2.0, 5.0))

        leverage_proxy = phase_frame["leverage_proxy_sample"].dropna()
        if leverage_proxy.empty:
            leverage_factor = defaults["leverage_factor"]["params"]["value"]
        else:
            leverage_factor = max(float(np.median(np.abs(leverage_proxy.to_numpy()))), 1.0)

        return {
            "inventory_sensitivity_vg": common_behavior["inventory_sensitivity_vg"],
            "event_trigger_price_bps": scalar_value(event_trigger),
            "max_order_frac_depth": defaults["max_order_frac_depth"],
            "leverage_factor": scalar_value(leverage_factor),
            "order_type_market_fraction": defaults["order_type_market_fraction"],
        }

    if agent_type == "noise_trader":
        size_values = phase_frame["order_size_multiplier"].dropna()
        if size_values.empty:
            aggressiveness_alpha = defaults["aggressiveness_alpha"]["params"]["value"]
        else:
            aggressiveness_alpha = float(np.mean(size_values.to_numpy()))

        lambda_anchor = anchors.get("noise_trader_lambda", {}).get(phase)
        if lambda_anchor is None:
            lambda_values = phase_frame["noise_trader_lambda_anchor"].dropna()
            lambda_anchor = float(np.median(lambda_values.to_numpy())) if not lambda_values.empty else 0.0

        return {
            "aggressiveness_alpha": scalar_value(aggressiveness_alpha),
            "inventory_sensitivity_vg": common_behavior["inventory_sensitivity_vg"],
            "arrival_rate_lambda": scalar_value(float(lambda_anchor)),
            "order_type_market_fraction": defaults["order_type_market_fraction"],
        }

    raise ValueError(f"Unsupported agent_type: {agent_type}")


def build_phase_output(
    parsed: pd.DataFrame,
    anchors: dict[str, Any],
    agent_type: str,
    phase: str,
    min_group_size: int,
    stats_module: Any | None,
) -> dict[str, Any]:
    phase_frame = parsed[(parsed["agent_type"] == agent_type) & (parsed["phase"] == phase)].copy()
    fit_frame, fit_source, warnings = choose_fit_frame(parsed, agent_type, phase, min_group_size)
    if fit_source == "excluded_missing_phase":
        return {
            "sample_size": 0,
            "fit_sample_size": 0,
            "fit_source": fit_source,
            "excluded_from_fitting": True,
            "warnings": warnings,
            "common_behavior": None,
            "behavioral_priors": None,
        }

    common_behavior = fit_common_behavior(fit_frame, agent_type, fit_source, stats_module)
    agent_specific = build_agent_specific_priors(agent_type, phase, phase_frame, common_behavior, anchors)

    return {
        "sample_size": int(len(phase_frame)),
        "fit_sample_size": int(len(fit_frame)),
        "fit_source": fit_source,
        "excluded_from_fitting": False,
        "warnings": warnings,
        "common_behavior": common_behavior,
        "behavioral_priors": agent_specific,
    }


def main() -> None:
    args = parse_args()
    input_csv, output_json = choose_paths(args)

    frame = load_frame(input_csv)
    anchors = load_anchors(args.anchors_json)
    parsed = parsed_only(frame)
    stats_module = try_import_scipy()
    stats_backend = "scipy" if stats_module is not None else "moments_fallback"
    synthetic_rows = 0
    if "sample_origin" in frame.columns:
        synthetic_rows = int((frame["sample_origin"] == "anchor_imputed_phase_sample").sum())

    if args.dry_run:
        frame = frame.head(DRY_RUN_SAMPLES)
        parsed = parsed_only(frame)
        if "sample_origin" in frame.columns:
            synthetic_rows = int((frame["sample_origin"] == "anchor_imputed_phase_sample").sum())

    print("=" * 70)
    print("Script 16: Fit Behavioral Priors")
    print("=" * 70)
    print(f"  Input CSV    : {input_csv}")
    print(f"  Output JSON  : {output_json}")
    print(f"  Anchors JSON : {args.anchors_json}")
    print(f"  Parsed rows  : {len(parsed)}")
    print(f"  Excluded synthetic rows : {synthetic_rows}")
    print(f"  Fit backend  : {stats_backend}")
    print(f"  Min group n  : {args.min_group_size}")

    output: dict[str, Any] = {
        "metadata": {
            "schema_version": "phase1_behavioral_priors.v1",
            "source_csv": input_csv.name,
            "anchors_json": args.anchors_json.name,
            "parsed_rows": int(len(parsed)),
            "minimum_group_size": int(args.min_group_size),
            "fit_backend": stats_backend,
            "excluded_synthetic_rows": synthetic_rows,
            "agent_types": list(AGENT_CONFIGS.keys()),
            "phases": PHASES,
            "observed_phases": sorted(parsed["phase"].dropna().astype(str).unique().tolist()) if not parsed.empty else [],
        }
    }

    fallback_count = 0
    excluded_count = 0
    for agent_type in AGENT_CONFIGS:
        output[agent_type] = {}
        for phase in PHASES:
            phase_output = build_phase_output(
                parsed=parsed,
                anchors=anchors,
                agent_type=agent_type,
                phase=phase,
                min_group_size=args.min_group_size,
                stats_module=stats_module,
            )
            if phase_output["fit_source"] == "excluded_missing_phase":
                excluded_count += 1
            elif phase_output["fit_source"] != "phase_fit":
                fallback_count += 1
            output[agent_type][phase] = phase_output

    atomic_write_json(output_json, output)

    print(f"\n  Agent-phase entries written: {len(AGENT_CONFIGS) * len(PHASES)}")
    print(f"  Fallback entries           : {fallback_count}")
    print(f"  Excluded missing phases    : {excluded_count}")
    print("Done.")


if __name__ == "__main__":
    main()